defmodule ExPesa.Util.Records do
  @moduledoc """
  Extracts all records information from an Erlang file.
  Returns a keyword list of {record_name, fields} tuples where record_name is the name of an extracted record and fields is a list of {field, value} tuples representing the fields for that record.
  """

  require Record
  import Record, only: [defrecord: 2, extract: 2]

  @public_key "public_key/include/public_key.hrl"

  defrecord :Certificate, extract(:Certificate, from_lib: @public_key)
  defrecord :TBSCertificate, extract(:TBSCertificate, from_lib: @public_key)
  defrecord :SubjectPublicKeyInfo, extract(:SubjectPublicKeyInfo, from_lib: @public_key)
end

defmodule ExPesa.Util do
  require ExPesa.Util.Records
  @moduledoc false

  @doc false
  @spec get_url(String.t(), String.t()) :: String.t()
  def get_url(live_url, sandbox_url) do
    cond do
      Mix.env() == :prod -> live_url
      Application.get_env(:ex_pesa, :force_live_url) == "YES" -> live_url
      true -> sandbox_url
    end
  end

  @doc """
  Security Credentials
  M-Pesa Core authenticates a transaction by decrypting the security credentials. Security credentials are generated by encrypting the base64 encoded initiator password with M-Pesa’s public key, a X509 certificate.
  The algorithm for generating security credentials is as follows:
  Write the unencrypted password into a byte array.
  Encrypt the array with the M-Pesa public key certificate. Use the RSA algorithm, and use PKCS #1.5 padding (not OAEP), and add the result to the encrypted stream.
  Convert the resulting encrypted byte array into a string using base64 encoding. The resulting base64 encoded string is the security credential.
  ## Parameters
  attrs:- a map containing:
  - `CertFile` - This is the M-Pesa public key certificate used to encrypt your plain password.
    There are 2 types of certificates.
      - sandox - https://developer.safaricom.co.ke/sites/default/files/cert/cert_sandbox/cert.cer
      - production - https://developer.safaricom.co.ke/sites/default/files/cert/cert_prod/cert.cer
  - `Password` - This is a plain unencrypted password.
    Environment
      - production - set password from the organization portal.
      - sandbox - use anything as your sandbox password.
  ## Example
      iex> certfile = "-----BEGIN CERTIFICATE-----\nMIIGKzCCBROgAwIBAgIQDL7NH8cxSdUpl0ihH0A1wTANBgkqhkiG9w0BAQsFADBN\nMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMScwJQYDVQQDEx5E\naWdpQ2VydCBTSEEyIFNlY3VyZSBTZXJ2ZXIgQ0EwHhcNMTgwODI3MDAwMDAwWhcN\nMTkwNDA0MTIwMDAwWjBuMQswCQYDVQQGEwJLRTEQMA4GA1UEBxMHTmFpcm9iaTEW\nMBQGA1UEChMNU2FmYXJpY29tIFBMQzETMBEGA1UECxMKRGlnaXRhbCBJVDEgMB4G\nA1UEAxMXc2FuZGJveC5zYWZhcmljb20uY28ua2UwggEiMA0GCSqGSIb3DQEBAQUA\nA4IBDwAwggEKAoIBAQC78yeC/wLoZY6TJeqc4g/9eAKIpeCwEsjX09pD8ZxAGXqT\nOi7ssdIGJBPmJZNeEVyf8ocFhisCuLngJ9Z5e/AvH52PhrEFmVu2D03zSf4C+rhZ\nndEKP6G79pUAb/bemOliU9zM8xYYkpCRzPWUzk6zSDarg0ZDLw5FrtZj/VJ9YEDL\nWGgAfwExEgSN3wjyUlJ2UwI3wqQXLka0VNFWoZxUH5j436gbSWRIL6NJUmrq8V8S\naTEPz3eJHj3NOToDu245c7VKdF/KExyZjRjD2p5I+Aip80TXzKlZj6DjMb3DlfXF\nHsnu0+1uJE701mvKX7BiscxKr8tCRphL63as4dqvAgMBAAGjggLkMIIC4DAfBgNV\nHSMEGDAWgBQPgGEcgjFh1S8o541GOLQs4cbZ4jAdBgNVHQ4EFgQUzZmY7ZORLw9w\nqRbAQN5m9lJ28qMwIgYDVR0RBBswGYIXc2FuZGJveC5zYWZhcmljb20uY28ua2Uw\nDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBr\nBgNVHR8EZDBiMC+gLaArhilodHRwOi8vY3JsMy5kaWdpY2VydC5jb20vc3NjYS1z\naGEyLWc2LmNybDAvoC2gK4YpaHR0cDovL2NybDQuZGlnaWNlcnQuY29tL3NzY2Et\nc2hhMi1nNi5jcmwwTAYDVR0gBEUwQzA3BglghkgBhv1sAQEwKjAoBggrBgEFBQcC\nARYcaHR0cHM6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzAIBgZngQwBAgIwfAYIKwYB\nBQUHAQEEcDBuMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20w\nRgYIKwYBBQUHMAKGOmh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2Vy\ndFNIQTJTZWN1cmVTZXJ2ZXJDQS5jcnQwCQYDVR0TBAIwADCCAQUGCisGAQQB1nkC\nBAIEgfYEgfMA8QB2AKS5CZC0GFgUh7sTosxncAo8NZgE+RvfuON3zQ7IDdwQAAAB\nZXs1FvEAAAQDAEcwRQIgBzVMkm7SNprjJ1GBqiXIc9rNzY+y7gt6s/O02oMkyFoC\nIQDBuThGlpmUKpeZoHhK6HGwB4jDMIecmKaOcMS18R2jxwB3AId1v+dZfPiMQ5lf\nvfNu/1aNR1Y2/0q1YMG06v9eoIMPAAABZXs1F8IAAAQDAEgwRgIhAIRq2XFiC+RS\nuDCYq8ICJg0QafSV+e9BLpJnElEdaSjiAiEAyiiW4vxwv4cWcAXE6FAipctyUBs6\nbE5QyaCnmNpoDiQwDQYJKoZIhvcNAQELBQADggEBAB0YoWve9Sxhb0PBS3Hc46Rf\na7H1jhHuwE+UyscSQsdJdk8uPAgDuKRZMvJPGEaCkNHm36NfcaXXFjPOl7LI1d1a\n9zqSP0xeZBI6cF0x96WuQGrI9/WR2tfxjmaUSp8a/aJ6n+tZA28eJZNPrIaMm+6j\ngh7AkKnqcf+g8F/MvCCVdNAiVMdz6UpCscf6BRPHNZ5ifvChGh7aUKjrVLLuF4Ls\nHE05qm6HNyV5eTa6wvcbc4ewguN1UDZvPWetSyfBk10Wbpor4znQ4TJ3Y9uCvsJH\n41ldblDvZZ2z4kB2UYQ7iBkPlJSxSOaFgW/GGDXq49sz/995xzhVITHxh2SdLkI=\n-----END CERTIFICATE-----\n"
      iex> password = "Safaricom133"
      iex> ExPesa.Util.generate_security_credential(%{CertFile: certfile, Password: password})
  """

  def generate_security_credential(%{CertFile: certfile, Password: password})
      when certfile != nil and password != nil do
    cert_text =
      certfile |> String.trim() |> String.split(~r{\n  *}, trim: true) |> Enum.join("\n")

    # 1) Decode the certificate.
    [pem_entry] = :public_key.pem_decode(cert_text)
    cert_decoded = :public_key.pem_entry_decode(pem_entry)

    # 2) Extract public key.
    plk =
      cert_decoded
      |> ExPesa.Util.Records."Certificate"(:tbsCertificate)
      |> ExPesa.Util.Records."TBSCertificate"(:subjectPublicKeyInfo)
      |> ExPesa.Util.Records."SubjectPublicKeyInfo"(:subjectPublicKey)

    public_key = :public_key.der_decode(:RSAPublicKey, plk)

    # 3) Encrypt the plain password text
    ciphertext =
      :public_key.encrypt_public(password, public_key, [{:rsa_pad, :rsa_pkcs1_padding}])

    # 4) Base64 encode and return the result
    :base64.encode(ciphertext)
  end

  def generate_security_credential(%{}) do
    nil
  end

  def get_security_credential_for(key) do
    case Application.get_env(:ex_pesa, :mpesa)[key][:security_credential] do
      nil ->
        cert = Application.get_env(:ex_pesa, :mpesa)[:cert]
        password = Application.get_env(:ex_pesa, :mpesa)[key][:password]
        generate_security_credential(%{CertFile: cert, Password: password})

      credential ->
        credential
    end
  end
end
